const identityTypes = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",

  CONFIRM_REQUEST: "CONFIRM_REQUEST",
  CONFIRM_SUCCESS: "CONFIRM_SUCCESS",
  CONFIRM_FAILURE: "CONFIRM_FAILURE",

  FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAILURE: "FORGOT_PASSWORD_FAILURE",

  FORGOT_CONFIRM_PASSWORD_REQUEST: "FORGOT_CONFIRM_PASSWORD_REQUEST",
  FORGOT_CONFIRM_PASSWORD_SUCCESS: "FORGOT_CONFIRM_PASSWORD_SUCCESS",
  FORGOT_CONFIRM_PASSWORD_FAILURE: "FORGOT_CONFIRM_PASSWORD_FAILURE",

  SET_TOKEN: "SET_TOKEN",
  SET_TOKEN_FAILURE: "SET_TOKEN_FAILURE",

  RESET_MESSAGE: "RESET_MESSAGE"
};

export default identityTypes;
