export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const CONFIRM_REQUEST = 'CONFIRM_REQUEST';
export const CONFIRM_SUCCESS = 'CONFIRM_SUCCESS';
export const CONFIRM_FAILURE = 'CONFIRM_FAILURE';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

export const FORGOT_CONFIRM_PASSWORD_REQUEST = 'FORGOT_CONFIRM_PASSWORD_REQUEST';
export const FORGOT_CONFIRM_PASSWORD_SUCCESS = 'FORGOT_CONFIRM_PASSWORD_SUCCESS';
export const FORGOT_CONFIRM_PASSWORD_FAILURE = 'FORGOT_CONFIRM_PASSWORD_FAILURE';

export const SET_TOKEN = 'SET_TOKEN';
export const SET_TOKEN_FAILURE = 'SET_TOKEN_FAILURE';

export const RESET_MESSAGE = 'RESET_MESSAGE';