const currencyTypes = {
  GET_CURRENCY_LIST_REQUEST: "GET_CURRENCY_LIST_REQUEST",
  GET_CURRENCY_LIST_SUCCESS: "GET_CURRENCY_LIST_SUCCESS",
  GET_CURRENCY_LIST_FAILURE: "GET_CURRENCY_LIST_FAILURE",

  GET_CURRENCY: "GET_CURRENCY",

  CREATE_CURRENCY_REQUEST: "CREATE_CURRENCY_REQUEST",
  CREATE_CURRENCY_SUCCESS: "CREATE_CURRENCY_SUCCESS",
  CREATE_CURRENCY_FAILURE: "CREATE_CURRENCY_FAILURE",

  UPDATE_CURRENCY_REQUEST: "UPDATE_CURRENCY_REQUEST",
  UPDATE_CURRENCY_SUCCESS: "UPDATE_CURRENCY_SUCCESS",
  UPDATE_CURRENCY_FAILURE: "UPDATE_CURRENCY_FAILURE",

  DELETE_CURRENCY_REQUEST: "DELETE_CURRENCY_REQUEST",
  DELETE_CURRENCY_SUCCESS: "DELETE_CURRENCY_SUCCESS",
  DELETE_CURRENCY_FAILURE: "DELETE_CURRENCY_FAILURE",
};

export default currencyTypes;
